### ISSUE TITLE
Remove console logs

### ISSUE THREAD

**Issue by micahlt** [wasteofplus/wasteof.plus#38]
There appears to be a lot of unnecessary console logging happening in the latest release.  This should probably be removed.
![image](https://github.com/imadeanaccount1/wasteof.plus/assets/28816297/1c277495-5a03-4440-a450-4d0f56b0dcaf)

**Comment by imadeanaccount1** [comment]
@micahlt Thank you for your first issue!

I am planning to remove unnecessary console.logs before publishing wasteof.plus, but after porting it for Firefox (which I am almost done with) and merging PR #22 (which includes desktop notifications, extension popup updates, and more.).

**Comment by imadeanaccount1** [comment]
@micahlt Progress on this issue, the PR #108 hides console logs in production, so that logs only show when loaded through dev mode in Chrome/Firefox. Going to merge and close this tomorrow! :)

![image](https://github.com/wasteofplus/wasteof.plus/assets/138229538/1e4e5ef5-1a93-4401-a639-5835f259d128)
