### ISSUE TITLE
The extension popup is unstyled on Edge

### ISSUE THREAD

**Issue by mybearworld** [wasteofplus/wasteof.plus#48]
![image](https://github.com/imadeanaccount1/wasteof.plus/assets/130385691/1900c764-e080-4bf3-91a4-b1a32b1c35ce)

**Comment by imadeanaccount1** [comment]
I'll investigate this.

**Comment by imadeanaccount1** [comment]
@mybearworld How did you install the extension. In this version, `npm run ci` must be run before the extension can be loaded into Chrome, Edge, or Opera. In this version, the extension popup uses tailwind, which is why the dependencies must be installed. Alternatively, you can try the release artifact in this Action (which has the node_modules folder): https://github.com/imadeanaccount1/wasteof.plus/actions/runs/5693794806

**Comment by mybearworld** [comment]
`npm run ci` errors as the script "ci" is not existent. Installing the dependencies does fix this, though.

**Comment by imadeanaccount1** [comment]
sorry, npm ci is the right command 😅
